resources:
  - deployment.yaml

namespace: <OPENTERRASCAN_NAMESPACE>

commonLabels:
  app: openterrascan

configMapGenerator:
  - name: openterrascan-config
    files:
      - config.toml=config/config.toml
