apiVersion: v1
name: openterrascan
version: 1.0.0
appVersion: v1.6.0
description: A Helm chart for running openterrascan in server mode
icon: https://raw.githubusercontent.com/tenable/openterrascan/master/docs/img/openterrascan-icon-white.png
home: https://github.com/tenable/openterrascan
keywords:
  - openterrascan
  - opa
  - security
  - webhook
  - validating-webhook
  - admission-controller
  - admission
sources:
  - https://github.com/tenable/openterrascan
maintainers:
  - name: openterrascan
    email: openterrascan@tenable.com
