openterrascan_webhook_key: terrakey
openterrascan_container_image: tenable/openterrascan:1.16.0
openterrascan_service_type: ClusterIP
use_debug: true
# provide secrets for admission controller
secrets:
  tlsCertFilePath: ""
  tlsKeyFilePath: ""
cert_secret_name: openterrascancerts
ssh_secret_name: openterrascanssh
config_name: openterrascanconfig
replicas: 1
name: openterrascan
persistence:
  enabled: false
  existingclaim: openterrascanPvc
webhook:
  mode: false
  name: webhook.openterrascan.io
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions:
    - "v1"
    - "v1beta1"
  apiGroups:
    - "apps"
    - ""
  resources:
    - "deployments"
    - "pods"
  apiVersions:
    - "*"
  operations:
    - CREATE
    - UPDATE
