apiVersion: apps/v1
kind: Deployment
metadata:
  name: openterrascan
spec:
  template:
    spec:
      containers:
      - name: openterrascan-server
        volumeMounts:
        - mountPath: /data/certs
          name: openterrascan-certs-secret
          readOnly: true
        args:
        - >
          openterrascan server --cert-path /data/certs/server.crt --key-path /data/certs/server.key -l debug -c /data/config/config.toml
      volumes:
      #add a secret for the tls certificates
      - name: openterrascan-certs-secret
        secret:
          secretName: openterrascan-certs-secret
