resources:
  - ../base
  - service.yaml

namespace: <OPENTERRASCAN_NAMESPACE>

commonLabels:
  app: openterrascan

secretGenerator:
  - name: openterrascan-certs-secret
    files:
      - server.key=certs/server.key
      - server.crt=certs/server.crt

patchesStrategicMerge:
  - deployment-certs.yaml
